---
language: ruby
rvm:
- 2.0.0
script:
- rake
after_success:
- rake learnery:version
- rake learnery:deploy["learnery-staging-webdev"]
env:
  global:
    secure: |-
      H/sjuQG5rHo19sni7/b+pIXWzY8VFRIQbuMiqrO9FgXoG3t98dimixlEZ07l
      dcOAfrXJMYiD4/TaFZwxd1f/tnw1+hJEJGDNIdQKxC0WiznZN1uVvyA9xUAl
      o4mwydazHvCORP3YPFojOGFs2M2RhDegyALhKFpYiI6wWJU4qC8=
